#!/usr/bin/env python3
"""Generate repository README and traditional awesome-list files for a hub."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Any

import yaml


def _project(config: dict[str, Any]) -> dict[str, Any]:
    value = config.get("project", {})
    return value if isinstance(value, dict) else {}


def _repo_slug(github_url: str) -> str:
    match = re.search(r"github\.com[:/](.+?)(?:\.git)?/?$", github_url)
    return match.group(1) if match else "your-org/awesome-hub"


def _paper_link(paper: dict[str, Any]) -> str:
    links = paper.get("links") if isinstance(paper.get("links"), dict) else {}
    return str(links.get("paper") or links.get("arxiv") or links.get("pdf") or "").strip()


def _category(paper: dict[str, Any]) -> str:
    paper_type = paper.get("paper_type")
    if isinstance(paper_type, list) and paper_type:
        return ", ".join(str(item) for item in paper_type[:2])
    if isinstance(paper_type, str) and paper_type:
        return paper_type
    return str(paper.get("category") or "paper")


def _short_text(value: Any, limit: int = 180) -> str:
    text = re.sub(r"\s+", " ", str(value or "")).strip()
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "..."


def _score(paper: dict[str, Any]) -> str:
    score = paper.get("score") if isinstance(paper.get("score"), dict) else {}
    value = score.get("read_first_score", score.get("total", paper.get("score")))
    if isinstance(value, (int, float)):
        return f"{value:.1f}".rstrip("0").rstrip(".")
    return ""


def _year_value(paper: dict[str, Any]) -> int:
    try:
        return int(paper.get("year") or 0)
    except (TypeError, ValueError):
        return 0


def _stats(papers: list[dict[str, Any]], data_dir: Path) -> dict[str, int]:
    datasets = yaml.safe_load((data_dir / "datasets.yaml").read_text(encoding="utf-8")) if (data_dir / "datasets.yaml").exists() else []
    research_runs = yaml.safe_load((data_dir / "research_runs.yaml").read_text(encoding="utf-8")) if (data_dir / "research_runs.yaml").exists() else []
    return {
        "papers": len(papers),
        "datasets": len(datasets) if isinstance(datasets, list) else 0,
        "research_runs": len(research_runs) if isinstance(research_runs, list) else 0,
        "with_analysis": sum(1 for paper in papers if paper.get("analysis")),
        "with_openalex": sum(1 for paper in papers if isinstance(paper.get("openalex"), dict) and paper["openalex"].get("id")),
    }


def load_config(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) if path.exists() else {}
    return data if isinstance(data, dict) else {}


def load_papers(data_dir: Path) -> list[dict[str, Any]]:
    papers_path = data_dir / "papers.yaml"
    data = yaml.safe_load(papers_path.read_text(encoding="utf-8")) if papers_path.exists() else []
    papers = [paper for paper in data if isinstance(paper, dict)] if isinstance(data, list) else []
    return sorted(papers, key=lambda p: (-_year_value(p), -float(_score(p) or 0), str(p.get("title") or "")))


def render_readme(config: dict[str, Any], papers: list[dict[str, Any]], data_dir: Path) -> str:
    project = _project(config)
    name = str(project.get("name") or "Awesome Hub")
    description = str(project.get("description") or "A curated research hub.")
    site_url = str(project.get("site_url") or "").rstrip("/")
    github_url = str(project.get("github_url") or "")
    generator_repo = str(project.get("generator_repo") or "jin-s13/awesome-hub-generator")
    stats = _stats(papers, data_dir)
    zh_url = f"{site_url}/zh/" if site_url else ""
    en_url = f"{site_url}/en/" if site_url else site_url

    links = []
    if zh_url:
        links.append(f"[中文 Web UI]({zh_url})")
    if en_url:
        links.append(f"[English Web UI]({en_url})")
    links.append("[Traditional Awesome List](./AWESOME.md)")
    links.append(f"[Generator](https://github.com/{generator_repo})")

    return "\n".join(
        [
            f"# {name}",
            "",
            "<p align=\"center\">",
            f"  <a href=\"{zh_url}\"><img alt=\"中文 Web UI\" src=\"https://img.shields.io/badge/%E4%B8%AD%E6%96%87-Web%20UI-2563eb?style=for-the-badge\"></a>",
            f"  <a href=\"{en_url}\"><img alt=\"English Web UI\" src=\"https://img.shields.io/badge/English-Web%20UI-0f172a?style=for-the-badge\"></a>",
            "  <a href=\"./AWESOME.md\"><img alt=\"Traditional Awesome List\" src=\"https://img.shields.io/badge/Awesome-List-f59e0b?style=for-the-badge\"></a>",
            f"  <a href=\"https://github.com/{generator_repo}\"><img alt=\"Generated by awesome-hub-generator\" src=\"https://img.shields.io/badge/Generated%20by-awesome--hub--generator-22c55e?style=for-the-badge\"></a>",
            "</p>",
            "",
            description,
            "",
            "A living, research-oriented awesome list for world models: papers, benchmarks, datasets,",
            "citation signals, TLDRs, deep analysis notes, and literature-review style summaries.",
            "",
            " ".join(links),
            "",
            "## What This Hub Provides",
            "",
            "| Surface | Purpose |",
            "| --- | --- |",
            f"| Web interface | Browse, search, filter, rank, and read bilingual paper analysis. Start from the [Chinese UI]({zh_url}) or [English UI]({en_url}). |",
            "| Traditional awesome list | A GitHub-native table for quick scanning, linking, and downstream reuse: [AWESOME.md](./AWESOME.md). |",
            f"| Structured metadata | Machine-readable data lives on the `main` branch under `data/`, `assets/`, and `resource/`. |",
            f"| Generator source | The site is maintained by [`{generator_repo}`](https://github.com/{generator_repo}). |",
            "",
            "## Snapshot",
            "",
            f"- Papers indexed: **{stats['papers']}**",
            f"- Datasets indexed: **{stats['datasets']}**",
            f"- Papers with deep analysis: **{stats['with_analysis']}**",
            f"- Papers matched with OpenAlex metadata: **{stats['with_openalex']}**",
            f"- Research runs: **{stats['research_runs']}**",
            "",
            "## Repository Layout",
            "",
            "| Path / branch | Use it for |",
            "| --- | --- |",
            "| `main:data/` | Paper, dataset, survey, trend, and run metadata. |",
            "| `main:assets/` | Teaser images and generated media assets. |",
            "| `main:resource/` | Per-paper research notes and deeper generated artifacts. |",
            "| `main:AWESOME.md` | Traditional awesome-list reading experience. |",
            "| `gh-pages` | Built static website only. Use it for browser hosting, not as the metadata source. |",
            "",
            "## Daily Updates",
            "",
            "GitHub Actions refreshes the hub every day at **UTC 00:00 / Beijing 08:00**.",
            "The pipeline searches recent papers, updates datasets, fetches teaser images, enriches",
            "OpenAlex citation metadata, backfills TLDR/deep analysis fields, rebuilds the Astro site,",
            "and publishes GitHub Pages.",
            "",
            "Required repository secret: `ARK_API_KEY`.",
            "Optional secrets: `ARK_API_BASE_URL`, `ARK_MODEL_NAME`, `SMART_MODEL_NAME`,",
            "`MINERU_API_KEY`, `OPENALEX_API_KEY`, `OPENALEX_MAILTO`.",
            "",
            "## Local Preview",
            "",
            "```bash",
            "python awesome-hub-generator/scripts/build.py --data-dir data --output website --render-only --skip-build",
            "cd website",
            "npm install",
            "npm run dev",
            "```",
            "",
            "---",
            "",
            f"Generated and maintained with [{generator_repo}](https://github.com/{generator_repo}).",
            "",
        ]
    )


def render_awesome(config: dict[str, Any], papers: list[dict[str, Any]], data_dir: Path) -> str:
    project = _project(config)
    name = str(project.get("name") or "Awesome Hub")
    description = str(project.get("description") or "A curated research hub.")
    site_url = str(project.get("site_url") or "").rstrip("/")
    zh_url = f"{site_url}/zh/" if site_url else ""
    rows = [
        f"# {name}: Traditional Awesome List",
        "",
        description,
        "",
        f"- Web UI: [{zh_url}]({zh_url})" if zh_url else "- Web UI: see the repository README.",
        "- Project README: [README.md](./README.md)",
        "",
        "## Papers",
        "",
        "| Year | Score | Type | Paper | TLDR |",
        "| --- | ---: | --- | --- | --- |",
    ]
    for paper in papers:
        title = str(paper.get("title") or "Untitled")
        link = _paper_link(paper)
        paper_cell = f"[{title}]({link})" if link else title
        rows.append(
            "| "
            + " | ".join(
                [
                    str(paper.get("year") or ""),
                    _score(paper),
                    _category(paper),
                    paper_cell.replace("|", "\\|"),
                    _short_text(paper.get("tldr") or paper.get("abstract"), 180).replace("|", "\\|"),
                ]
            )
            + " |"
        )
    rows.extend(["", "---", "", f"Total papers: **{len(papers)}**."])
    return "\n".join(rows) + "\n"


def write_repo_files(config_path: Path, data_dir: Path, output_dir: Path) -> None:
    config = load_config(config_path)
    papers = load_papers(data_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "README.md").write_text(render_readme(config, papers, data_dir), encoding="utf-8")
    (output_dir / "AWESOME.md").write_text(render_awesome(config, papers, data_dir), encoding="utf-8")
    print(f"[repo-readme] wrote README.md and AWESOME.md ({len(papers)} papers)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a hub repository README and AWESOME.md")
    parser.add_argument("--config", required=True, help="Path to awesome.yaml")
    parser.add_argument("--data-dir", required=True, help="Path to hub data directory")
    parser.add_argument("--output-dir", required=True, help="Repository root where README.md/AWESOME.md are written")
    args = parser.parse_args()
    write_repo_files(Path(args.config), Path(args.data_dir), Path(args.output_dir))


if __name__ == "__main__":
    main()
